export const ADD_EXHIBIT = 'ADD_EXHIBIT';
export const SEARCH_EXHIBIT = 'SEARCH_EXHIBIT';
export const FILTER_EXHIBIT = 'FILTER_EXHIBIT';
export const RESET_FILTER_EXHIBIT = 'RESET_FILTER_EXHIBIT';
export const SHOW_ADD_MODAL = 'SHOW_ADD_MODAL';
export const HIDE_ADD_MODAL = 'HIDE_ADD_MODAL';